export const GET_INDEX_HTML = 'GET_INDEX_HTML';
export const POPULATE_CATEGORIES = 'POPULATE_CATEGORIES';
export const USER_FB_DATA = 'USER_FB_DATA';
export const GET_FOLDER_NAME = 'GET_FOLDER_NAME';
